name: Update Age in README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Age in README
      run: |
        today=$(date '+%m-%d')
        birthday="04-04"
        if [ "$today" == "$birthday" ]; then
          current_year=$(date '+%Y')
          birth_year=2000
          age=$(($current_year - $birth_year))
          sed -i "s/{{age}}/$age/" README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m
          git push
        fi
