name: Update Birth Year

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  update-birth-year:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Calculate and Update Birth Year
      run: |
        today=$(date '+%m-%d')
        birthday="04-04"
        if [ "$today" == "$birthday" ]; then
          current_year=$(date '+%Y')
          birth_year=$(($current_year - 24))
          sed -i "s/Born in [0-9]\{4\}/Born in $birth_year/" README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update birth year"
          git push
        fi
